### ISSUE TITLE
Additional Features

### ISSUE THREAD

**Issue by moazkassab** [KenAragorn/create_flutter_provider_app#4]
Hey, I'm really impressed with this starter architecture. Would be really nice if you added some additional features: 
1. Other authentication methods (google, facebook, twitter, biometrics)
2. Responsive UI boilerplate code (sounds challenging to add responsiveness as a boilerplate code! Maybe settle with deviceWidth and deviceHeight as constants)
3. Firebase Queries service. Some examples that came to my mind:
  - Query a collection based on one value
  - Query a collection based on multiple values, .where('docField', 'in', '[values]')
  - Query SubCollections with same name, subCollectionNames.where('docField', 'condition', 'value').groupByParent('parentCollection') 
  - order a collection based on field, ascending or descending.
4. Firebase messaging service, for sending notifications.
5. Firebase Storage service.
6. Firebase Analytics Service.
7. String Validators Service. Check out [this implementation](https://github.com/bizz84/codewithandrea_flutter_packages/blob/master/packages/string_validators/lib/string_validators.dart)
8. Error handling service. 

I know that's a lot, but you're doing a great job so far. This boilerplate structure has a high potential of easing the process for many developers.

**Comment by KenAragorn** [comment]
Hi @moazkassab . Thanks for write up.

Yes, the other authentication methods is part of my list. In fact, I'm writing a real world application for multiple users, using this project. It almost done soon, and will then update this core master repo for people to view.

The project includes:

- Firebase Storage service
- Error handling service
- Some of the query of sub collections

Once I push it to the Play Store, I will then update this repo with it. 

The list you shared is definitely helps me a lot - on further improve this. 

Yes, will update - stay tune. :)

**Comment by moazkassab** [comment]
Thanks @KenAragorn ,keep up the good work.
